alter system set listen_addresses = '*';
alter system set max_connections = 2000;
alter system set work_mem = '16MB';
alter system set shared_buffers = '@SHARED_BUFFERS@';  -- 假设 buffer_shared 为 128MB
alter system set checkpoint_completion_target = 0.8;
alter system set log_destination = 'csvlog';
alter system set logging_collector = on;
alter system set log_directory = 'hgdb_log';
alter system set log_filename = 'highgodb_%d.log';
alter system set log_rotation_age = '1d';
alter system set log_rotation_size = 0;
alter system set log_truncate_on_rotation = on;
alter system set log_statement = 'ddl';
alter system set log_connections = on;
alter system set log_disconnections = on;
alter system set checkpoint_timeout = '30min';
alter system set maintenance_work_mem = '1GB';
alter system set archive_mode = @ARCHIVE_MODE@;  -- 使用占位符
alter system set archive_timeout = '30min';
alter system set archive_command = 'cp %p @ARCHIVE_DIR@/%f';  -- 使用占位符
alter system set log_line_prefix = '%m [%p] %a %u %d %r %h';
alter system set nls_length_semantics = 'char';
